title: The best title ever
author: Bob Jenkins
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Description of what the site/blog is about 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
